<?php

declare(strict_types=1);

return [
    ['name' => 'Classic Smirk', 'text' => '( ͡° ͜ʖ ͡°)', 'category' => 'Classic Faces'],
    ['name' => 'Stone Face', 'text' => 'ಠ_ಠ', 'category' => 'Classic Faces'],
    ['name' => 'Side Eye', 'text' => '(¬_¬)', 'category' => 'Classic Faces'],
    ['name' => 'Big Reveal', 'text' => '( •_•)>⌐■-■', 'category' => 'Classic Faces'],
    ['name' => 'Cool Finish', 'text' => '(⌐■_■)', 'category' => 'Classic Faces'],
    ['name' => 'Tiny Shock', 'text' => '(☉_☉)', 'category' => 'Classic Faces'],
    ['name' => 'Pleading Stare', 'text' => '(ಥ﹏ಥ)', 'category' => 'Classic Faces'],
    ['name' => 'Sleepy Blink', 'text' => '(-_-) zzz', 'category' => 'Classic Faces'],

    ['name' => 'Happy Beam', 'text' => '(＾▽＾)', 'category' => 'Happy and Hype'],
    ['name' => 'Joy Spark', 'text' => '(*^▽^*)', 'category' => 'Happy and Hype'],
    ['name' => 'Bouncy Hello', 'text' => '\(^o^)/', 'category' => 'Happy and Hype'],
    ['name' => 'Excited Squeal', 'text' => 'Ｏ(≧▽≦)Ｏ', 'category' => 'Happy and Hype'],
    ['name' => 'Radiant Smile', 'text' => '(o^▽^o)', 'category' => 'Happy and Hype'],
    ['name' => 'Party Pop', 'text' => '＼(≧▽≦)／', 'category' => 'Happy and Hype'],

    ['name' => 'Meltdown Tears', 'text' => '(T_T)', 'category' => 'Sad Hours'],
    ['name' => 'Dramatic Cry', 'text' => '(;﹏;)', 'category' => 'Sad Hours'],
    ['name' => 'Rain Cloud', 'text' => '(｡•́︿•̀｡)', 'category' => 'Sad Hours'],
    ['name' => 'Heartbreak Sigh', 'text' => '(╥﹏╥)', 'category' => 'Sad Hours'],
    ['name' => 'Quiet Deflate', 'text' => '(︶︹︺)', 'category' => 'Sad Hours'],

    ['name' => 'Battle Ready', 'text' => 'ლ(ಠ益ಠლ)', 'category' => 'Angry and Intense'],
    ['name' => 'Squared Up', 'text' => '(ง •̀_•́)ง', 'category' => 'Angry and Intense'],
    ['name' => 'Stubborn Flex', 'text' => 'ᕙ(⇀‸↼‶)ᕗ', 'category' => 'Angry and Intense'],
    ['name' => 'Glare Mode', 'text' => '(╬ Ò﹏Ó)', 'category' => 'Angry and Intense'],
    ['name' => 'Steam Ears', 'text' => '٩(╬ʘ益ʘ╬)۶', 'category' => 'Angry and Intense'],
    ['name' => 'Goblin Threat', 'text' => '(ಠ益ಠ)', 'category' => 'Angry and Intense'],

    ['name' => 'Full Shrug', 'text' => '¯\\_(ツ)_/¯', 'category' => 'Shrugs and Chaos'],
    ['name' => 'Jazz Hands Chaos', 'text' => 'ヽ༼ຈل͜ຈ༽ﾉ', 'category' => 'Shrugs and Chaos'],
    ['name' => 'Magic Problem', 'text' => '(∩^o^)⊃━☆ﾟ.*･｡ﾟ', 'category' => 'Shrugs and Chaos'],
    ['name' => 'Panic Scatter', 'text' => 'ヽ(゜Q。)ノ？', 'category' => 'Shrugs and Chaos'],
    ['name' => 'Confused Orbit', 'text' => '◎[▪‿▪]◎', 'category' => 'Shrugs and Chaos'],
    ['name' => 'Who Knows', 'text' => '┐(￣ヘ￣)┌', 'category' => 'Shrugs and Chaos'],

    ['name' => 'Table Respecter', 'text' => '┬─┬ノ( º _ ºノ)', 'category' => 'Table Drama'],
    ['name' => 'Table Flipper', 'text' => '(╯°□°）╯︵ ┻━┻', 'category' => 'Table Drama'],
    ['name' => 'Rage Flipper', 'text' => '(ノಠ益ಠ)ノ彡┻━┻', 'category' => 'Table Drama'],
    ['name' => 'Double Flip', 'text' => '┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻', 'category' => 'Table Drama'],
    ['name' => 'Desk Slam', 'text' => '(╯°□°)╯︵ ʞooqǝɔɐɟ', 'category' => 'Table Drama'],

    ['name' => 'Flex Appeal', 'text' => 'ᕦ(ò_óˇ)ᕤ', 'category' => 'Victory Laps'],
    ['name' => 'Speed Walk', 'text' => 'ᕕ( ᐛ )ᕗ', 'category' => 'Victory Laps'],
    ['name' => 'Happy Launch', 'text' => '╰(°▽°)╯', 'category' => 'Victory Laps'],
    ['name' => 'Sparkle Toss', 'text' => '(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧', 'category' => 'Victory Laps'],
    ['name' => 'Double Finger Guns', 'text' => '(☞ﾟヮﾟ)☞', 'category' => 'Victory Laps'],
    ['name' => 'Party Burst', 'text' => '(ﾉ≧∀≦)ﾉ', 'category' => 'Victory Laps'],
    ['name' => 'Winner Energy', 'text' => 'Ꮚ˘ ꈊ ˘ Ꮚ', 'category' => 'Victory Laps'],
    ['name' => 'Mission Accomplished', 'text' => 'ヽ(^o^)丿', 'category' => 'Victory Laps'],

    ['name' => 'Bear Hello', 'text' => 'ʕ•ᴥ•ʔ', 'category' => 'Soft and Sweet'],
    ['name' => 'Incoming Hug', 'text' => '(づ｡◕‿‿◕｡)づ', 'category' => 'Soft and Sweet'],
    ['name' => 'Kiss Delivery', 'text' => '(づ￣ ³￣)づ', 'category' => 'Soft and Sweet'],
    ['name' => 'Puppy Smile', 'text' => '(ᵔᴥᵔ)', 'category' => 'Soft and Sweet'],
    ['name' => 'Cheerful Wave', 'text' => 'ヽ(•‿•)ノ', 'category' => 'Soft and Sweet'],
    ['name' => 'Gentle Stardust', 'text' => '(੭ˊᵕˋ)੭* ੈ✩‧₊˚', 'category' => 'Soft and Sweet'],
    ['name' => 'Blushing Peek', 'text' => '(⁄ ⁄•⁄ω⁄•⁄ ⁄)', 'category' => 'Soft and Sweet'],
    ['name' => 'Tiny Love', 'text' => '(♡˙︶˙♡)', 'category' => 'Soft and Sweet'],

    ['name' => 'Finger Guns Deluxe', 'text' => '(☞ ͡° ͜ʖ ͡°)☞', 'category' => 'Goblin Energy'],
    ['name' => 'Scheming Face', 'text' => '( ͠° ͟ʖ ͡°)', 'category' => 'Goblin Energy'],
    ['name' => 'Blink and Wonder', 'text' => '(⊙_☉)', 'category' => 'Goblin Energy'],
    ['name' => 'Mischief Gremlin', 'text' => 'ψ(｀∇´)ψ', 'category' => 'Goblin Energy'],
    ['name' => 'Sneaky Plot', 'text' => '(¬‿¬)', 'category' => 'Goblin Energy'],
    ['name' => 'Chaos Smile', 'text' => '¯\\(°_o)/¯', 'category' => 'Goblin Energy'],

    ['name' => 'Furby Bean Stare', 'text' => '^(◕ 3 ◕)^', 'category' => 'Beans'],
    ['name' => 'Bean Blink', 'text' => '^(⌒ 3 ⌒)^', 'category' => 'Beans'],
    ['name' => 'Bean Floof', 'text' => '<(o 3 o)>', 'category' => 'Beans'],
    ['name' => 'Midnight Bean', 'text' => '^(• 3 •)^', 'category' => 'Beans'],
    ['name' => 'Snack Bean Squeak', 'text' => '<(◔ 3 ◔)>', 'category' => 'Beans'],
    ['name' => 'Bean Side Glance', 'text' => '^(¬ 3 ¬)^', 'category' => 'Beans'],

    ['name' => 'Confused Tilt', 'text' => '(´・ω・`)', 'category' => 'Confusion/Awkward'],
    ['name' => 'Blank Stare', 'text' => '(´−ω−`)', 'category' => 'Confusion/Awkward'],
    ['name' => 'Lost Soul', 'text' => '(´・_・`)', 'category' => 'Confusion/Awkward'],
    ['name' => 'Sweat Drop Worry', 'text' => '(´；ω；`)', 'category' => 'Confusion/Awkward'],
    ['name' => 'Question Mark Face', 'text' => '(´・ ▽ ・`)', 'category' => 'Confusion/Awkward'],

    ['name' => 'Salute Ready', 'text' => '(๑•́ ▽ •̀๑)', 'category' => 'Actions/Gestures'],
    ['name' => 'Facepalm Moment', 'text' => '(´；ρ；`)', 'category' => 'Actions/Gestures'],
    ['name' => 'Tippy Toes Sneak', 'text' => '(´▽｀)', 'category' => 'Actions/Gestures'],
    ['name' => 'Thumbs Up Cheer', 'text' => '(๑•́ ω •̀๑)و', 'category' => 'Actions/Gestures'],
    ['name' => 'Crawling Advance', 'text' => 'ヾ(•ω•`)o', 'category' => 'Actions/Gestures'],
    ['name' => 'Confident Nod', 'text' => '(๑•́ω•̀๑)و', 'category' => 'Actions/Gestures'],
    ['name' => 'Pray Hands', 'text' => '(´；ω；`)ﾉ', 'category' => 'Actions/Gestures'],

    ['name' => 'Ultra Wink', 'text' => '( ͡ ͜ʖ ͡ )', 'category' => 'Classic Faces'],
    ['name' => 'Awkward Chuckle', 'text' => '(´Д`)ﾊﾊ…', 'category' => 'Classic Faces'],
    ['name' => 'Derp Mode', 'text' => 'ヽ(´ー`)ノ', 'category' => 'Classic Faces'],
];
